services:
  ssot-api-helper:
    platform: linux/arm64
    image: ssot-api-helper:latest
    build:
      context: .
      dockerfile: Dockerfile.helper
    volumes:
      - .:/code
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_TOKEN
      - AWS_XRAY_SDK_ENABLED=0
      - GIT_VERSION_TAG
      - BUILD_VERSION
      - ENVIRONMENT
      - PYLINTHOME=.
